# Generated by Django 4.0.5 on 2022-07-07 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('problem_difficulty', models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], default='easy', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.FileField(upload_to='test_inputs/')),
                ('test_output', models.FileField(upload_to='test_outputs')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c++', 'cpp')], max_length=10)),
                ('verdict', models.CharField(choices=[('PS', 'processing'), ('WA', 'wrong answer'), ('AC', 'accepted'), ('TLE', 'time limit excedded'), ('MLE', 'memory limit excedded')], max_length=10)),
                ('code_file', models.FileField(upload_to='code_file/')),
                ('Timestamp', models.TimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
    ]
